name: flutter_example
description: Flutter Example

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: any
  sqflite: ^2.0.3+1
  animate_do: ^2.1.0
  flutter_slidable: ^2.0.0
  quickalert: ^1.0.0
  lottie: ^2.4.0
  flutter_zoom_drawer: ^3.1.1
  iconly: ^1.0.1
  zoom_tap_animation: ^1.1.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
